#!/usr/bin/env node
// W13 A-CUES: the four shared sound cues (six files) that the Godot game and the web twin both play. SYNTH: every
// sample is computed here from oscillators, seeded noise, biquad filters and envelopes. Nothing is downloaded,
// sampled or generated by a service; no keys, no network, no dependencies, and no Math.random (seeded mulberry32).
//
//   node tools/audio/synth-cues.mjs              rewrite public/assets/audio/synth_*.wav (byte-identical every run)
//   node tools/audio/synth-cues.mjs --out <dir>  write the same files somewhere else (the unit test does this)
//
// Output: 16-bit PCM mono WAV, 44.1 kHz, each cue peak-normalised to -3 dBFS, DC-blocked and faded out at the end.
// The character follows the web's procedural voices (src/client/audio/presets-weapons.ts, presets-objective.ts):
//   rifle_shot         the Squeaker Rifle report: noise crack, sine thump, band-passed blast, a short yard tail,
//                      the bolt's click and a faint rubber squeak riding it, all through a soft-clip grit stage
//   hit_confirm        the shooter's "it landed": a bright two-partial tick over a small dull thwack, ~0.1 s
//   slab_tick          a soft pitched blip (A5, the third of the music's key of F) with a quick downward settle
//   slab_tick_enemy    the same idea a fourth lower (D5), low-passed, sagging, with a muffled under-thump
//   match_end_win      snare pickup, two bugle C5s, then the full F major chord over timpani and a crash
//   match_end_lose     a timpani hit under a dark B-flat minor brass chord that sags a semitone, a second, lower drum
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const SR = 44100;
export const PEAK_DBFS = -3;
const TAU = Math.PI * 2;
const NYQ_SAFE = 16000; // additive voices stop adding partials above this (no aliasing)
const FLOOR = Math.log(1e-4); // envelopes decay to -80 dB, like the web's exponentialRamp to 0.0001

// ------------------------------------------------------------------------------------------------ building blocks

/** Seeded PRNG (mulberry32, the same one as src/shared/rng.ts). */
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** A noise source: white, pink (Kellet economy filter) or brown, as in src/client/audio/synth.ts. */
function noise(kind, seed) {
  const r = mulberry32(seed);
  let b0 = 0, b1 = 0, b2 = 0, br = 0;
  return () => {
    const w = r() * 2 - 1;
    if (kind === 'white') return w;
    if (kind === 'pink') {
      b0 = 0.99765 * b0 + w * 0.099046; b1 = 0.963 * b1 + w * 0.2965164; b2 = 0.57 * b2 + w * 1.0526913;
      return (b0 + b1 + b2 + w * 0.1848) * 0.18;
    }
    br = (br + 0.02 * w) / 1.02;
    return br * 3.5;
  };
}

/** RBJ biquad (lowpass / highpass / bandpass with 0 dB peak). `set` may be called per sample for sweeps. */
class Biquad {
  constructor(type, f, q) {
    this.type = type;
    this.x1 = this.x2 = this.y1 = this.y2 = 0;
    this.set(f, q);
  }
  set(f, q) {
    const w = (TAU * Math.min(f, SR * 0.45)) / SR, c = Math.cos(w), s = Math.sin(w), al = s / (2 * q);
    let b0, b1, b2;
    if (this.type === 'lowpass') { b0 = (1 - c) / 2; b1 = 1 - c; b2 = b0; }
    else if (this.type === 'highpass') { b0 = (1 + c) / 2; b1 = -(1 + c); b2 = b0; }
    else { b0 = al; b1 = 0; b2 = -al; }
    const a0 = 1 + al;
    this.b0 = b0 / a0; this.b1 = b1 / a0; this.b2 = b2 / a0; this.a1 = (-2 * c) / a0; this.a2 = (1 - al) / a0;
  }
  run(x) {
    const y = this.b0 * x + this.b1 * this.x1 + this.b2 * this.x2 - this.a1 * this.y1 - this.a2 * this.y2;
    this.x2 = this.x1; this.x1 = x; this.y2 = this.y1; this.y1 = y;
    return y;
  }
}

/** Attack-decay: linear 0 → peak over `a`, then exponential to -80 dB over `d`. */
function ad(t, at, a, peak, d) {
  const u = t - at;
  if (u < 0) return 0;
  if (u < a) return (peak * u) / a;
  const v = (u - a) / d;
  return v >= 1 ? 0 : peak * Math.exp(FLOOR * v);
}

/** Attack-hold-release. */
function ahr(t, at, a, peak, hold, r) {
  const u = t - at;
  if (u < 0) return 0;
  if (u < a) return (peak * u) / a;
  if (u < a + hold) return peak;
  const v = (u - a - hold) / r;
  return v >= 1 ? 0 : peak * Math.exp(FLOOR * v);
}

/** Exponential glide from f0 to f1 over `dur` starting at `at`. */
function glide(t, at, f0, f1, dur) {
  const k = Math.min(1, Math.max(0, (t - at) / dur));
  return f0 * Math.pow(f1 / f0, k);
}

/** A phase-accumulating additive oscillator: amps[k] is the level of partial k+1. Band-limited by construction. */
function partials(amps) {
  let ph = 0;
  return (f) => {
    let y = 0;
    for (let k = 0; k < amps.length; k++) {
      if ((k + 1) * f > NYQ_SAFE) break;
      if (amps[k] !== 0) y += amps[k] * Math.sin(TAU * (k + 1) * ph);
    }
    ph += f / SR;
    ph -= Math.floor(ph);
    return y;
  };
}
const sine = () => partials([1]);
const SQUARE = Array.from({ length: 15 }, (_, k) => (k % 2 === 0 ? 1 / (k + 1) : 0));
const TRIANGLE = Array.from({ length: 15 }, (_, k) => (k % 2 === 0 ? (k % 4 === 0 ? 1 : -1) / ((k + 1) * (k + 1)) : 0));

/** Adds fn(t) into buf for samples in [at, at + dur). fn is called once per sample, in order. */
function add(buf, at, dur, fn) {
  const i0 = Math.max(0, Math.round(at * SR)), i1 = Math.min(buf.length, Math.round((at + dur) * SR));
  for (let i = i0; i < i1; i++) buf[i] += fn(i / SR);
}

const seconds = (s) => new Float64Array(Math.round(s * SR));

// ------------------------------------------------------------------------------------------------ the cues

/** Squeaker Rifle: a compact report. Crack, thump, blast and tail share a soft-clip grit bus; bolt and squeak ride clean. */
function rifleShot() {
  const bus = seconds(0.24), out = seconds(0.24);
  { // crack: the transient
    const nz = noise('white', 0x5101), hp = new Biquad('highpass', 1900, 0.7);
    add(bus, 0, 0.06, (t) => hp.run(nz()) * ad(t, 0, 0.001, 0.42, 0.028));
  }
  { // body thump
    const o = sine();
    add(bus, 0, 0.2, (t) => o(glide(t, 0, 125, 52.5, 0.07)) * ad(t, 0, 0.002, 0.45, 0.14));
  }
  { // blast: the muzzle's bark
    const nz = noise('pink', 0x5102), bp = new Biquad('bandpass', 780, 1.1);
    add(bus, 0, 0.2, (t) => bp.run(nz()) * ad(t, 0.002, 0.003, 0.3, 0.15));
  }
  { // tail: the yard answering back, a closing low-pass
    const nz = noise('brown', 0x5103), lp = new Biquad('lowpass', 1100, 0.6);
    add(bus, 0.02, 0.22, (t) => { lp.set(glide(t, 0.02, 1100, 260, 0.18), 0.6); return lp.run(nz()) * ahr(t, 0.02, 0.02, 0.14, 0.03, 0.15); });
  }
  const g = Math.tanh(1.8);
  for (let i = 0; i < bus.length; i++) out[i] = Math.tanh(1.8 * bus[i]) / g;
  { // bolt click: a band-passed square blip and a hiss of metal
    const o = partials(SQUARE), bp = new Biquad('bandpass', 3300, 4), nz = noise('white', 0x5104), hp = new Biquad('highpass', 4000, 0.7);
    add(out, 0.018, 0.04, (t) => bp.run(o(3300)) * ad(t, 0.018, 0.001, 0.14, 0.018) + hp.run(nz()) * ad(t, 0.018, 0.001, 0.084, 0.012));
  }
  { // the faint rubber squeak riding the bolt (the pet joke, kept to a whisper)
    const o = partials(TRIANGLE), bp = new Biquad('bandpass', 2900, 3);
    add(out, 0.03, 0.07, (t) => bp.run(o(glide(t, 0.03, 2500, 3300, 0.03))) * ad(t, 0.03, 0.004, 0.05, 0.03));
  }
  return out;
}

/** Hit confirm: a crisp, small "tk" (two bright partials) over a short mid slap. Tonal and tiny next to the shot. */
function hitConfirm() {
  const out = seconds(0.1);
  { // the tick
    const o = partials(SQUARE), bp = new Biquad('bandpass', 2400, 3);
    add(out, 0, 0.06, (t) => bp.run(o(2150)) * ad(t, 0, 0.001, 0.42, 0.03));
  }
  { // a glassy top on the tick
    const o = sine();
    add(out, 0.003, 0.07, (t) => o(3150) * ad(t, 0.003, 0.001, 0.2, 0.045));
  }
  { // thwack: a slap of band-passed noise
    const nz = noise('pink', 0x4101), bp = new Biquad('bandpass', 1100, 0.9);
    add(out, 0, 0.06, (t) => bp.run(nz()) * ad(t, 0, 0.001, 0.3, 0.03));
  }
  { // a small body under it
    const o = sine();
    add(out, 0, 0.1, (t) => o(glide(t, 0, 190, 85, 0.045)) * ad(t, 0, 0.0015, 0.26, 0.05));
  }
  return out;
}

/** Slab point, our side: a soft A5 blip that settles from just above pitch, with a quick octave shimmer. */
function slabTick() {
  const out = seconds(0.13);
  const o = partials([1, 0.16, 0.05]);
  add(out, 0, 0.13, (t) => o(glide(t, 0, 940, 880, 0.012)) * ad(t, 0, 0.004, 0.5, 0.12));
  const s = sine();
  add(out, 0, 0.08, (t) => s(1760) * ad(t, 0, 0.002, 0.07, 0.05));
  return out;
}

/** Slab point, their side: a fourth lower (D5), low-passed, sagging, with a muffled under-thump. Lower and duller. */
function slabTickEnemy() {
  const out = seconds(0.13);
  const o = partials([1, 0.05]), lp = new Biquad('lowpass', 1000, 0.7);
  add(out, 0, 0.13, (t) => lp.run(o(glide(t, 0, 600, 560, 0.1))) * ad(t, 0, 0.007, 0.5, 0.11));
  const s = sine();
  add(out, 0, 0.1, (t) => s(glide(t, 0, 300, 270, 0.06)) * ad(t, 0, 0.006, 0.14, 0.07));
  return out;
}

// --- match-end instruments

/** Additive brass: a saw-like series whose brightness rises with level (the "blat"), with optional sag and vibrato. */
function brass(buf, at, f, hold, peak, opt = {}) {
  const a = opt.attack ?? 0.03, r = opt.release ?? 0.4, bright = opt.bright ?? 1;
  let ph = 0, vph = 0;
  const breath = noise('pink', opt.seed ?? 0x6100), bp = new Biquad('bandpass', Math.min(6000, f * 3), 2);
  add(buf, at, a + hold + r, (t) => {
    const e = ahr(t, at, a, 1, hold, r);
    let fr = f;
    if (opt.sag) fr *= glide(t, opt.sag.at, 1, opt.sag.to, opt.sag.dur);
    if (opt.vib) {
      const ramp = Math.min(1, Math.max(0, (t - opt.vib.at) / opt.vib.ramp));
      fr *= 1 + opt.vib.depth * ramp * Math.sin(TAU * vph);
      vph += opt.vib.rate / SR;
      vph -= Math.floor(vph);
    }
    const roll = Math.exp(-(1.25 - 0.85 * bright * e)); // partial-to-partial rolloff: brighter when louder
    let y = 0, amp = 1;
    for (let n = 1; n <= 16 && n * fr < 9000; n++) { y += (amp / n) * Math.sin(TAU * n * ph); amp *= roll; }
    ph += fr / SR;
    ph -= Math.floor(ph);
    const air = bp.run(breath()) * ad(t, at, 0.004, 0.25, 0.05);
    return peak * (e * y + air);
  });
}

/** Snare: band-passed noise (the shell), high-passed noise (the wires) and a short tonal body. */
function snare(buf, at, level, seed) {
  const nz = noise('white', seed), bp = new Biquad('bandpass', 1800, 0.8), hp = new Biquad('highpass', 4500, 0.7), o = sine();
  add(buf, at, 0.16, (t) => {
    const x = nz();
    return bp.run(x) * ad(t, at, 0.001, level, 0.12) + hp.run(x) * ad(t, at, 0.001, level * 0.5, 0.07)
      + o(glide(t, at, 200, 170, 0.03)) * ad(t, at, 0.001, level * 0.6, 0.05);
  });
}

/** Timpani: inharmonic membrane partials (upper ones dying first), a slight pitch settle, and a felt mallet thump. */
function timpani(buf, at, f, level, decay, seed) {
  const ratios = [1, 1.5, 1.99, 2.44], amps = [1, 0.5, 0.3, 0.15], ph = [0, 0, 0, 0];
  const nz = noise('pink', seed), lp = new Biquad('lowpass', 500, 0.7);
  add(buf, at, decay + 0.01, (t) => {
    const base = glide(t, at, f * 1.02, f, 0.05);
    let y = 0;
    for (let k = 0; k < 4; k++) {
      y += amps[k] * Math.sin(TAU * ph[k]) * ad(t, at, 0.004, 1, decay / (1 + k));
      ph[k] += (base * ratios[k]) / SR;
      ph[k] -= Math.floor(ph[k]);
    }
    return level * y + lp.run(nz()) * ad(t, at, 0.002, level * 0.5, 0.05);
  });
}

/** Crash: high-passed noise with a short bloom and a long fall. */
function crash(buf, at, level, seed) {
  const nz = noise('white', seed), hp = new Biquad('highpass', 5200, 0.7);
  add(buf, at, 1.0, (t) => hp.run(nz()) * ahr(t, at, 0.01, level, 0.08, 0.8));
}

const N = { Bb2: 116.54, Bb3: 233.08, Db4: 277.18, F4: 349.23, A4: 440, C5: 523.25, F5: 698.46, F2: 87.31 };

/** We won: a snare pickup, the bugle (C C), then the full F major chord, F5 on top, over timpani and a crash. */
function matchEndWin() {
  const out = seconds(1.5);
  for (let i = 0; i < 8; i++) snare(out, i * 0.024, 0.08 + 0.12 * (i / 7), 0x7100 + i);
  brass(out, 0.19, N.C5, 0.05, 0.16, { attack: 0.012, release: 0.06, bright: 1.1, seed: 0x7110 });
  brass(out, 0.29, N.C5, 0.05, 0.16, { attack: 0.012, release: 0.06, bright: 1.1, seed: 0x7111 });
  const vib = { at: 0.7, ramp: 0.25, depth: 0.007, rate: 5.5 };
  brass(out, 0.4, N.F4, 0.5, 0.085, { release: 0.55, vib, seed: 0x7120 });
  brass(out, 0.4, N.A4, 0.5, 0.085, { release: 0.55, vib, seed: 0x7121 });
  brass(out, 0.4, N.C5, 0.5, 0.085, { release: 0.55, vib, seed: 0x7122 });
  brass(out, 0.4, N.F5, 0.5, 0.15, { release: 0.55, vib, bright: 1.1, seed: 0x7123 });
  snare(out, 0.4, 0.2, 0x7130);
  timpani(out, 0.4, N.F2, 0.55, 0.7, 0x7140);
  crash(out, 0.4, 0.09, 0x7150);
  return out;
}

/** We lost: a drum and snare hit under a dark B-flat minor chord that sags a semitone, then a second, lower drum. */
function matchEndLose() {
  const out = seconds(1.3);
  snare(out, 0, 0.16, 0x8100);
  timpani(out, 0, N.Bb2, 0.55, 0.8, 0x8110);
  const sag = { at: 0.42, to: 0.944, dur: 0.5 };
  for (const [i, f] of [N.Bb3, N.Db4, N.F4].entries()) {
    brass(out, 0.02, f, 0.45, 0.1, { attack: 0.04, release: 0.7, bright: 0.55, sag, seed: 0x8120 + i });
  }
  brass(out, 0.02, N.Bb2, 0.45, 0.07, { attack: 0.05, release: 0.7, bright: 0.5, sag, seed: 0x8130 });
  timpani(out, 0.55, N.F2, 0.35, 0.7, 0x8140);
  return out;
}

export const CUES = [
  { name: 'rifle_shot', render: rifleShot },
  { name: 'hit_confirm', render: hitConfirm },
  { name: 'slab_tick', render: slabTick },
  { name: 'slab_tick_enemy', render: slabTickEnemy },
  { name: 'match_end_win', render: matchEndWin },
  { name: 'match_end_lose', render: matchEndLose },
];

// ------------------------------------------------------------------------------------------------ mastering + WAV

/** DC blocker (one-pole high-pass, ~20 Hz), a 4 ms raised-cosine fade-out, peak normalise, quantise to 16 bit. */
function master(x) {
  const R = 1 - (TAU * 20) / SR;
  let px = 0, py = 0;
  for (let i = 0; i < x.length; i++) { const y = x[i] - px + R * py; px = x[i]; py = y; x[i] = y; }
  const fade = Math.round(0.004 * SR);
  for (let i = 0; i < fade; i++) x[x.length - 1 - i] *= 0.5 - 0.5 * Math.cos((Math.PI * i) / fade);
  let peak = 0;
  for (let i = 0; i < x.length; i++) peak = Math.max(peak, Math.abs(x[i]));
  const k = (Math.pow(10, PEAK_DBFS / 20) * 32767) / peak;
  const pcm = new Int16Array(x.length);
  for (let i = 0; i < x.length; i++) pcm[i] = Math.max(-32768, Math.min(32767, Math.round(x[i] * k)));
  return pcm;
}

/** 16-bit PCM mono WAV at SR. */
function wav(pcm) {
  const data = pcm.length * 2, b = Buffer.alloc(44 + data);
  b.write('RIFF', 0, 'ascii'); b.writeUInt32LE(36 + data, 4); b.write('WAVE', 8, 'ascii');
  b.write('fmt ', 12, 'ascii'); b.writeUInt32LE(16, 16); b.writeUInt16LE(1, 20); b.writeUInt16LE(1, 22);
  b.writeUInt32LE(SR, 24); b.writeUInt32LE(SR * 2, 28); b.writeUInt16LE(2, 32); b.writeUInt16LE(16, 34);
  b.write('data', 36, 'ascii'); b.writeUInt32LE(data, 40);
  for (let i = 0; i < pcm.length; i++) b.writeInt16LE(pcm[i], 44 + i * 2);
  return b;
}

/** Renders every cue: [{ name, file, bytes, ms, peakDb, dcPct }]. */
export function renderCues() {
  return CUES.map(({ name, render }) => {
    const pcm = master(render());
    let peak = 0, sum = 0;
    for (const s of pcm) { peak = Math.max(peak, Math.abs(s)); sum += s; }
    return {
      name, file: `synth_${name}.wav`, bytes: wav(pcm),
      ms: (pcm.length / SR) * 1000, peakDb: 20 * Math.log10(peak / 32768), dcPct: (100 * Math.abs(sum / pcm.length)) / 32768,
    };
  });
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href;
if (isMain) {
  const at = process.argv.indexOf('--out');
  const dir = at > 0 ? resolve(process.argv[at + 1]) : join(dirname(fileURLToPath(import.meta.url)), '../../public/assets/audio');
  mkdirSync(dir, { recursive: true });
  console.log('| cue | file | duration | peak | size | DC |\n|---|---|---|---|---|---|');
  for (const c of renderCues()) {
    writeFileSync(join(dir, c.file), c.bytes);
    console.log(`| ${c.name} | ${c.file} | ${c.ms.toFixed(0)} ms | ${c.peakDb.toFixed(2)} dBFS | ${c.bytes.length} B (${(c.bytes.length / 1024).toFixed(1)} KB) | ${c.dcPct.toFixed(3)} % |`);
  }
  console.log(`wrote ${CUES.length} files to ${dir}`);
}
