// Snapshot bandwidth per client at 12 player entities (MASTER_PLAN §8.7 budget: <= 40 KB/s).
// Twelve clients random-walk/jump/sprint at 60 Hz; measured on the real frame path (JSON text) for
// the plain ServerMsg encoding ('raw', what the old server sent) and the per-connection delta
// encoding ('delta', src/host/wire.ts). A second pass adds synthetic combat events (every player
// firing ~8 shots/s with full-precision floats) to model a firefight. Writes artifacts/net-bandwidth.md.
import { describe, it, expect } from 'vitest';
import { mkdirSync, writeFileSync } from 'node:fs';
import { Sim } from '../../src/sim/sim';
import { Room } from '../../src/host/room';
import { LoopbackSession } from '../../src/client/net/loopback';
import type { WireEncoding } from '../../src/host/wire';
import { Btn, type InputCmd } from '../../src/shared/input';
import { mulberry32 } from '../../src/shared/rng';
import { EntityKind } from '../../src/shared/types';

const PLAYERS = 12;
const SECONDS = 6;

function walker(seed: number): (k: number) => Partial<InputCmd> {
  const rng = mulberry32(seed);
  let mx = 0, mz = 1, yaw = rng() * 6.28, until = 0, sprint = 0;
  return (k) => {
    if (k >= until) { until = k + 20 + Math.floor(rng() * 50); mx = rng() * 2 - 1; mz = rng() * 2 - 1; yaw += rng() * 3 - 1.5; sprint = rng() < 0.4 ? Btn.Sprint : 0; }
    return { mx, mz, yaw: yaw + Math.sin(k * 0.05) * 0.3, pitch: Math.sin(k * 0.03) * 0.3, buttons: sprint | (k % 83 < 9 ? Btn.Jump : 0) };
  };
}

async function measure(encoding: WireEncoding, combat: boolean): Promise<{ kbs: number; bytesPerSnap: number; entities: number }> {
  const sim = await Sim.create({ seed: 1 });
  const room = new Room(sim, { mode: 'net-bandwidth', botsPerTeam: [0, 0] }); // neutral mode: entity count stays 12
  const rng = mulberry32(99);
  const session = new LoopbackSession(room, () => {
    if (!combat) return;
    for (const e of sim.entities.values()) {
      if (e.kind !== EntityKind.Player || rng() > 8 / 60) continue;
      const dx = rng() - 0.5, dz = rng() - 0.5;
      sim.emit({ e: 'fire', id: e.id, wpn: 0, x: e.pos.x + 0.123456789, y: e.pos.y + 1.23456789, z: e.pos.z - 0.3456789, dx, dy: 0.01 * rng(), dz, hx: e.pos.x + dx * 30, hy: 1 + rng(), hz: e.pos.z + dz * 30, hit: -1 });
      if (rng() < 0.3) sim.emit({ e: 'hit', src: e.id, dst: e.id, dmg: 12.5 * rng(), x: e.pos.x + rng(), y: 1.1 + rng(), z: e.pos.z + rng(), crit: rng() < 0.1 });
    }
  });
  const net = { lagMs: 0, jitterMs: 0, lossPct: 0 };
  const clients = [];
  for (let i = 0; i < PLAYERS; i++) {
    clients.push(session.addClient({ id: `c${i}`, up: net, down: net, seed: i + 1, encoding, phaseMs: 1 + i * 1.3, input: walker(1000 + i), team: (i % 2) as 0 | 1, predict: i === 0 }));
  }
  await session.run(1000);
  const c = clients[0].link.stats;
  const b0 = c.snapBytes, s0 = c.snaps;
  await session.run(SECONDS * 1000);
  const res = { kbs: (c.snapBytes - b0) / 1024 / SECONDS, bytesPerSnap: (c.snapBytes - b0) / (c.snaps - s0), entities: sim.entities.size };
  for (const cl of [...session.clients]) session.removeClient(cl);
  room.dispose();
  return res;
}

describe('snapshot bandwidth at 12 entities', () => {
  it('stays under 40 KB/s per client with the delta encoding', async () => {
    const rows: string[] = [];
    const out: Record<string, number> = {};
    for (const combat of [false, true]) {
      for (const enc of ['raw', 'delta'] as WireEncoding[]) {
        const r = await measure(enc, combat);
        expect(r.entities).toBe(PLAYERS);
        out[`${enc}${combat ? '+combat' : ''}`] = r.kbs;
        rows.push(`| ${combat ? 'moving + firefight events' : 'all moving'} | ${enc} | ${r.entities} | ${r.bytesPerSnap.toFixed(0)} | ${r.kbs.toFixed(2)} |`);
      }
    }
    const table = ['| scenario | encoding | entities | bytes / snapshot | KB/s per client (30 Hz) |', '|---|---|---|---|---|', ...rows].join('\n');
    console.log(`\nSnapshot bandwidth (${PLAYERS} players, ${SECONDS} s)\n${table}\n`);
    mkdirSync('artifacts', { recursive: true });
    writeFileSync('artifacts/net-bandwidth.md', `# Snapshot bandwidth\n\nGenerated by tests/unit/net-bandwidth.test.ts on ${new Date().toISOString()}.\n\n${table}\n`);
    expect(out.delta).toBeLessThan(40);
    expect(out['delta+combat']).toBeLessThan(40);
    expect(out.delta).toBeLessThan(out.raw * 0.6);
  }, 120_000);
});
